// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.570000,HLS_SYN_LAT=61,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=357,HLS_SYN_LUT=282,HLS_VERSION=2022_2}" *)

module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        b_address0,
        b_ce0,
        b_q0,
        prod_address0,
        prod_ce0,
        prod_we0,
        prod_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] a_address0;
output   a_ce0;
input  [39:0] a_q0;
output  [2:0] b_address0;
output   b_ce0;
input  [39:0] b_q0;
output  [4:0] prod_address0;
output   prod_ce0;
output   prod_we0;
output  [15:0] prod_d0;

reg ap_idle;
reg[2:0] a_address0;
reg a_ce0;
reg b_ce0;
reg prod_ce0;
reg prod_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
wire    ap_block_state10_pp0_stage1_iter4;
wire    ap_block_state12_pp0_stage1_iter5;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln10_reg_475;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] indvar_flatten_load_reg_465;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state11_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln10_fu_197_p2;
wire   [2:0] add_ln10_fu_206_p2;
reg   [2:0] add_ln10_reg_479;
wire   [0:0] icmp_ln12_fu_212_p2;
reg   [0:0] icmp_ln12_reg_484;
wire   [2:0] select_ln10_fu_218_p3;
reg   [2:0] select_ln10_reg_493;
wire   [2:0] select_ln10_1_fu_226_p3;
reg   [2:0] select_ln10_1_reg_500;
wire   [7:0] grp_fu_131_p4;
reg   [7:0] tmp_reg_507;
wire    ap_block_pp0_stage1_11001;
wire   [7:0] grp_fu_141_p4;
reg   [7:0] tmp_s_reg_512;
wire   [7:0] grp_fu_151_p4;
reg   [7:0] tmp_1_reg_517;
wire   [7:0] grp_fu_161_p4;
reg   [7:0] tmp_2_reg_522;
wire   [7:0] trunc_ln10_1_fu_259_p1;
reg   [7:0] trunc_ln10_1_reg_532;
wire   [4:0] add_ln16_5_fu_270_p2;
reg   [4:0] add_ln16_5_reg_537;
reg   [4:0] add_ln16_5_reg_537_pp0_iter1_reg;
reg   [4:0] add_ln16_5_reg_537_pp0_iter2_reg;
reg   [4:0] add_ln16_5_reg_537_pp0_iter3_reg;
reg   [4:0] add_ln16_5_reg_537_pp0_iter4_reg;
wire   [7:0] select_ln10_2_fu_299_p3;
reg   [7:0] select_ln10_2_reg_547;
reg  signed [7:0] select_ln10_2_reg_547_pp0_iter2_reg;
wire   [7:0] select_ln10_3_fu_305_p3;
reg  signed [7:0] select_ln10_3_reg_552;
wire   [7:0] select_ln10_4_fu_311_p3;
reg   [7:0] select_ln10_4_reg_557;
reg  signed [7:0] select_ln10_4_reg_557_pp0_iter2_reg;
wire   [7:0] select_ln10_5_fu_317_p3;
reg  signed [7:0] select_ln10_5_reg_562;
wire   [7:0] select_ln10_6_fu_323_p3;
reg  signed [7:0] select_ln10_6_reg_567;
wire   [7:0] trunc_ln16_fu_329_p1;
reg   [7:0] trunc_ln16_reg_572;
reg  signed [7:0] trunc_ln16_reg_572_pp0_iter2_reg;
reg  signed [7:0] tmp_3_reg_577;
reg   [7:0] tmp_4_reg_582;
reg  signed [7:0] tmp_4_reg_582_pp0_iter2_reg;
reg  signed [7:0] tmp_5_reg_587;
reg  signed [7:0] tmp_6_reg_592;
wire   [15:0] grp_fu_379_p2;
reg  signed [15:0] mul_ln16_3_reg_637;
wire   [15:0] grp_fu_394_p2;
reg  signed [15:0] mul_ln16_1_reg_647;
wire  signed [15:0] grp_fu_423_p3;
reg   [15:0] add_ln16_1_reg_657;
wire  signed [15:0] grp_fu_430_p3;
reg  signed [15:0] add_ln16_reg_662;
wire   [15:0] grp_fu_437_p3;
reg  signed [15:0] add_ln16_2_reg_667;
(* use_dsp48 = "no" *) wire   [15:0] add_ln16_3_fu_415_p2;
reg   [15:0] add_ln16_3_reg_672;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln10_fu_192_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln10_1_fu_239_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln12_fu_263_p1;
wire   [63:0] zext_ln16_2_fu_419_p1;
reg   [2:0] j_fu_72;
wire   [2:0] add_ln12_fu_276_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_j_load;
reg   [2:0] i_fu_76;
reg   [2:0] ap_sig_allocacmp_i_1;
reg   [4:0] indvar_flatten_fu_80;
wire   [4:0] add_ln10_1_fu_234_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [4:0] tmp_8_fu_246_p3;
wire   [4:0] zext_ln16_fu_243_p1;
wire   [4:0] add_ln16_4_fu_253_p2;
wire   [4:0] zext_ln16_1_fu_267_p1;
wire   [7:0] trunc_ln10_fu_295_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to5;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_136;
reg    ap_condition_506;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mul_8s_8s_16_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_3_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_5_reg_587),
    .din1(select_ln10_5_reg_562),
    .ce(1'b1),
    .dout(grp_fu_379_p2)
);

matrix_mult_mul_8s_8s_16_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_3_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_3_reg_577),
    .din1(select_ln10_3_reg_552),
    .ce(1'b1),
    .dout(grp_fu_394_p2)
);

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_6_reg_592),
    .din1(select_ln10_6_reg_567),
    .din2(mul_ln16_3_reg_637),
    .ce(1'b1),
    .dout(grp_fu_423_p3)
);

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln16_reg_572_pp0_iter2_reg),
    .din1(select_ln10_2_reg_547_pp0_iter2_reg),
    .din2(mul_ln16_1_reg_647),
    .ce(1'b1),
    .dout(grp_fu_430_p3)
);

matrix_mult_mac_muladd_8s_8s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16ns_16_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_4_reg_582_pp0_iter2_reg),
    .din1(select_ln10_4_reg_557_pp0_iter2_reg),
    .din2(add_ln16_1_reg_657),
    .ce(1'b1),
    .dout(grp_fu_437_p3)
);

matrix_mult_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_506)) begin
            i_fu_76 <= 3'd0;
        end else if ((1'b1 == ap_condition_136)) begin
            i_fu_76 <= select_ln10_1_reg_500;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_506)) begin
            indvar_flatten_fu_80 <= 5'd0;
        end else if ((1'b1 == ap_condition_136)) begin
            indvar_flatten_fu_80 <= add_ln10_1_fu_234_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_506)) begin
            j_fu_72 <= 3'd0;
        end else if ((1'b1 == ap_condition_136)) begin
            j_fu_72 <= add_ln12_fu_276_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln10_fu_197_p2 == 1'd0))) begin
        add_ln10_reg_479 <= add_ln10_fu_206_p2;
        icmp_ln12_reg_484 <= icmp_ln12_fu_212_p2;
        select_ln10_1_reg_500 <= select_ln10_1_fu_226_p3;
        select_ln10_reg_493 <= select_ln10_fu_218_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln16_1_reg_657 <= grp_fu_423_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln16_2_reg_667 <= grp_fu_437_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln16_3_reg_672 <= add_ln16_3_fu_415_p2;
        icmp_ln10_reg_475 <= icmp_ln10_fu_197_p2;
        indvar_flatten_load_reg_465 <= ap_sig_allocacmp_indvar_flatten_load;
        mul_ln16_1_reg_647 <= grp_fu_394_p2;
        select_ln10_2_reg_547 <= select_ln10_2_fu_299_p3;
        select_ln10_2_reg_547_pp0_iter2_reg <= select_ln10_2_reg_547;
        select_ln10_3_reg_552 <= select_ln10_3_fu_305_p3;
        select_ln10_4_reg_557 <= select_ln10_4_fu_311_p3;
        select_ln10_4_reg_557_pp0_iter2_reg <= select_ln10_4_reg_557;
        select_ln10_5_reg_562 <= select_ln10_5_fu_317_p3;
        select_ln10_6_reg_567 <= select_ln10_6_fu_323_p3;
        tmp_3_reg_577 <= {{b_q0[15:8]}};
        tmp_4_reg_582 <= {{b_q0[23:16]}};
        tmp_4_reg_582_pp0_iter2_reg <= tmp_4_reg_582;
        tmp_5_reg_587 <= {{b_q0[31:24]}};
        tmp_6_reg_592 <= {{b_q0[39:32]}};
        trunc_ln16_reg_572 <= trunc_ln16_fu_329_p1;
        trunc_ln16_reg_572_pp0_iter2_reg <= trunc_ln16_reg_572;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_reg_475 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln16_5_reg_537 <= add_ln16_5_fu_270_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln16_5_reg_537_pp0_iter1_reg <= add_ln16_5_reg_537;
        add_ln16_5_reg_537_pp0_iter2_reg <= add_ln16_5_reg_537_pp0_iter1_reg;
        add_ln16_5_reg_537_pp0_iter3_reg <= add_ln16_5_reg_537_pp0_iter2_reg;
        add_ln16_5_reg_537_pp0_iter4_reg <= add_ln16_5_reg_537_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        mul_ln16_3_reg_637 <= grp_fu_379_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln16_reg_662 <= grp_fu_430_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln12_reg_484 == 1'd0))) begin
        tmp_1_reg_517 <= {{a_q0[31:24]}};
        tmp_2_reg_522 <= {{a_q0[39:32]}};
        tmp_reg_507 <= {{a_q0[15:8]}};
        tmp_s_reg_512 <= {{a_q0[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_reg_475 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln12_reg_484 == 1'd0))) begin
        trunc_ln10_1_reg_532 <= trunc_ln10_1_fu_259_p1;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            a_address0 = zext_ln10_1_fu_239_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            a_address0 = zext_ln10_fu_192_p1;
        end else begin
            a_address0 = 'bx;
        end
    end else begin
        a_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        a_ce0 = 1'b1;
    end else begin
        a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_reg_475 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 3'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_ce0 = 1'b1;
    end else begin
        b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        prod_ce0 = 1'b1;
    end else begin
        prod_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        prod_we0 = 1'b1;
    end else begin
        prod_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_1_fu_234_p2 = (indvar_flatten_load_reg_465 + 5'd1);

assign add_ln10_fu_206_p2 = (ap_sig_allocacmp_i_1 + 3'd1);

assign add_ln12_fu_276_p2 = (select_ln10_reg_493 + 3'd1);

assign add_ln16_3_fu_415_p2 = ($signed(add_ln16_2_reg_667) + $signed(add_ln16_reg_662));

assign add_ln16_4_fu_253_p2 = (tmp_8_fu_246_p3 + zext_ln16_fu_243_p1);

assign add_ln16_5_fu_270_p2 = (add_ln16_4_fu_253_p2 + zext_ln16_1_fu_267_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_136 = ((icmp_ln10_reg_475 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_506 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign b_address0 = zext_ln12_fu_263_p1;

assign grp_fu_131_p4 = {{a_q0[15:8]}};

assign grp_fu_141_p4 = {{a_q0[23:16]}};

assign grp_fu_151_p4 = {{a_q0[31:24]}};

assign grp_fu_161_p4 = {{a_q0[39:32]}};

assign icmp_ln10_fu_197_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_212_p2 = ((ap_sig_allocacmp_j_load == 3'd5) ? 1'b1 : 1'b0);

assign prod_address0 = zext_ln16_2_fu_419_p1;

assign prod_d0 = add_ln16_3_reg_672;

assign select_ln10_1_fu_226_p3 = ((icmp_ln12_fu_212_p2[0:0] == 1'b1) ? add_ln10_fu_206_p2 : ap_sig_allocacmp_i_1);

assign select_ln10_2_fu_299_p3 = ((icmp_ln12_reg_484[0:0] == 1'b1) ? trunc_ln10_fu_295_p1 : trunc_ln10_1_reg_532);

assign select_ln10_3_fu_305_p3 = ((icmp_ln12_reg_484[0:0] == 1'b1) ? grp_fu_131_p4 : tmp_reg_507);

assign select_ln10_4_fu_311_p3 = ((icmp_ln12_reg_484[0:0] == 1'b1) ? grp_fu_141_p4 : tmp_s_reg_512);

assign select_ln10_5_fu_317_p3 = ((icmp_ln12_reg_484[0:0] == 1'b1) ? grp_fu_151_p4 : tmp_1_reg_517);

assign select_ln10_6_fu_323_p3 = ((icmp_ln12_reg_484[0:0] == 1'b1) ? grp_fu_161_p4 : tmp_2_reg_522);

assign select_ln10_fu_218_p3 = ((icmp_ln12_fu_212_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_j_load);

assign tmp_8_fu_246_p3 = {{select_ln10_1_reg_500}, {2'd0}};

assign trunc_ln10_1_fu_259_p1 = a_q0[7:0];

assign trunc_ln10_fu_295_p1 = a_q0[7:0];

assign trunc_ln16_fu_329_p1 = b_q0[7:0];

assign zext_ln10_1_fu_239_p1 = add_ln10_reg_479;

assign zext_ln10_fu_192_p1 = ap_sig_allocacmp_i_1;

assign zext_ln12_fu_263_p1 = select_ln10_reg_493;

assign zext_ln16_1_fu_267_p1 = select_ln10_reg_493;

assign zext_ln16_2_fu_419_p1 = add_ln16_5_reg_537_pp0_iter4_reg;

assign zext_ln16_fu_243_p1 = select_ln10_1_reg_500;

endmodule //matrix_mult
