// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.430000,HLS_SYN_LAT=86,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=310,HLS_SYN_LUT=475,HLS_VERSION=2022_2}" *)

module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        a_address1,
        a_ce1,
        a_q1,
        b_address0,
        b_ce0,
        b_q0,
        b_address1,
        b_ce1,
        b_q1,
        prod_address0,
        prod_ce0,
        prod_we0,
        prod_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] a_address0;
output   a_ce0;
input  [7:0] a_q0;
output  [4:0] a_address1;
output   a_ce1;
input  [7:0] a_q1;
output  [4:0] b_address0;
output   b_ce0;
input  [7:0] b_q0;
output  [4:0] b_address1;
output   b_ce1;
input  [7:0] b_q1;
output  [4:0] prod_address0;
output   prod_ce0;
output   prod_we0;
output  [15:0] prod_d0;

reg ap_idle;
reg[4:0] a_address0;
reg a_ce0;
reg[4:0] a_address1;
reg a_ce1;
reg[4:0] b_address0;
reg b_ce0;
reg[4:0] b_address1;
reg b_ce1;
reg prod_ce0;
reg prod_we0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state6_pp0_stage2_iter1;
wire    ap_block_state9_pp0_stage2_iter2;
wire    ap_block_state12_pp0_stage2_iter3;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln10_reg_552;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg  signed [7:0] reg_191;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_state10_pp0_stage0_iter3;
wire    ap_block_state13_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage2_11001;
reg  signed [7:0] reg_195;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state5_pp0_stage1_iter1;
wire    ap_block_state8_pp0_stage1_iter2;
wire    ap_block_state11_pp0_stage1_iter3;
wire    ap_block_pp0_stage1_11001;
reg  signed [7:0] reg_199;
reg  signed [7:0] reg_203;
reg   [2:0] i_1_reg_542;
wire   [4:0] empty_fu_240_p2;
reg   [4:0] empty_reg_547;
wire   [0:0] icmp_ln10_fu_246_p2;
reg   [0:0] icmp_ln10_reg_552_pp0_iter1_reg;
reg   [0:0] icmp_ln10_reg_552_pp0_iter2_reg;
wire   [2:0] add_ln10_fu_261_p2;
reg   [2:0] add_ln10_reg_556;
wire   [0:0] icmp_ln12_fu_267_p2;
reg   [0:0] icmp_ln12_reg_561;
wire   [2:0] select_ln10_fu_273_p3;
reg   [2:0] select_ln10_reg_567;
reg   [2:0] select_ln10_reg_567_pp0_iter1_reg;
wire   [4:0] empty_7_fu_293_p2;
reg   [4:0] empty_7_reg_575;
wire   [2:0] select_ln10_1_fu_304_p3;
reg   [2:0] select_ln10_1_reg_580;
reg   [2:0] select_ln10_1_reg_580_pp0_iter1_reg;
wire   [4:0] select_ln10_2_fu_309_p3;
reg   [4:0] select_ln10_2_reg_586;
reg   [4:0] select_ln10_2_reg_586_pp0_iter1_reg;
wire   [4:0] add_ln10_1_fu_314_p2;
reg   [4:0] add_ln10_1_reg_593;
wire   [4:0] add_ln10_3_fu_320_p2;
reg   [4:0] add_ln10_3_reg_598;
wire   [4:0] zext_ln16_1_fu_326_p1;
reg   [4:0] zext_ln16_1_reg_603;
reg   [4:0] zext_ln16_1_reg_603_pp0_iter1_reg;
wire   [3:0] add_ln16_5_fu_332_p2;
reg   [3:0] add_ln16_5_reg_610;
wire   [4:0] add_ln16_7_fu_338_p2;
reg   [4:0] add_ln16_7_reg_615;
wire   [4:0] add_ln10_4_fu_367_p2;
reg   [4:0] add_ln10_4_reg_630;
wire   [4:0] add_ln16_8_fu_380_p2;
reg   [4:0] add_ln16_8_reg_645;
wire   [4:0] add_ln10_2_fu_419_p2;
reg   [4:0] add_ln10_2_reg_685;
wire   [4:0] add_ln16_6_fu_428_p2;
reg   [4:0] add_ln16_6_reg_695;
wire   [4:0] add_ln16_9_fu_475_p2;
reg   [4:0] add_ln16_9_reg_725;
reg   [4:0] add_ln16_9_reg_725_pp0_iter3_reg;
wire   [15:0] grp_fu_409_p2;
reg  signed [15:0] mul_ln16_3_reg_735;
wire   [15:0] grp_fu_437_p2;
reg  signed [15:0] mul_ln16_1_reg_745;
wire  signed [15:0] grp_fu_500_p3;
reg   [15:0] add_ln16_1_reg_755;
wire  signed [15:0] grp_fu_507_p3;
reg  signed [15:0] add_ln16_reg_760;
wire   [15:0] grp_fu_514_p3;
reg  signed [15:0] add_ln16_2_reg_765;
(* use_dsp48 = "no" *) wire   [15:0] add_ln16_3_fu_492_p2;
reg   [15:0] add_ln16_3_reg_770;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] add_ln10_1_cast_fu_359_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] add_ln10_3_cast_fu_363_p1;
wire   [63:0] zext_ln16_3_fu_372_p1;
wire   [63:0] zext_ln16_5_fu_376_p1;
wire   [63:0] add_ln10_4_cast_fu_385_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln16_6_fu_389_p1;
wire   [63:0] select_ln10_2_cast_fu_393_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln12_fu_401_p1;
wire   [63:0] add_ln10_2_cast_fu_467_p1;
wire   [63:0] zext_ln16_4_fu_471_p1;
wire   [63:0] zext_ln16_7_fu_496_p1;
reg   [2:0] j_fu_68;
wire   [2:0] add_ln12_fu_344_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_j_load;
reg   [2:0] i_fu_72;
reg   [2:0] ap_sig_allocacmp_i_1;
reg   [4:0] indvar_flatten_fu_76;
wire   [4:0] add_ln10_5_fu_252_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [4:0] tmp_fu_232_p3;
wire   [4:0] i_cast_fu_228_p1;
wire   [4:0] tmp_1_fu_285_p3;
wire   [4:0] add_ln10_cast_fu_281_p1;
wire   [3:0] zext_ln16_2_fu_329_p1;
wire   [4:0] tmp_2_fu_450_p3;
wire   [4:0] zext_ln16_fu_447_p1;
wire   [4:0] add_ln16_4_fu_457_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to4;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_150;
reg    ap_condition_573;
reg    ap_condition_292;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mul_8s_8s_16_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_3_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_203),
    .din1(reg_195),
    .ce(1'b1),
    .dout(grp_fu_409_p2)
);

matrix_mult_mul_8s_8s_16_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_3_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_199),
    .din1(reg_191),
    .ce(1'b1),
    .dout(grp_fu_437_p2)
);

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_203),
    .din1(reg_195),
    .din2(mul_ln16_3_reg_735),
    .ce(1'b1),
    .dout(grp_fu_500_p3)
);

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_199),
    .din1(reg_191),
    .din2(mul_ln16_1_reg_745),
    .ce(1'b1),
    .dout(grp_fu_507_p3)
);

matrix_mult_mac_muladd_8s_8s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16ns_16_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_q0),
    .din1(a_q0),
    .din2(add_ln16_1_reg_755),
    .ce(1'b1),
    .dout(grp_fu_514_p3)
);

matrix_mult_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_573)) begin
            i_fu_72 <= 3'd0;
        end else if ((1'b1 == ap_condition_150)) begin
            i_fu_72 <= select_ln10_1_fu_304_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_292)) begin
        if ((icmp_ln10_fu_246_p2 == 1'd0)) begin
            indvar_flatten_fu_76 <= add_ln10_5_fu_252_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_76 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_573)) begin
            j_fu_68 <= 3'd0;
        end else if ((1'b1 == ap_condition_150)) begin
            j_fu_68 <= add_ln12_fu_344_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_reg_552 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln10_1_reg_593 <= add_ln10_1_fu_314_p2;
        add_ln10_3_reg_598 <= add_ln10_3_fu_320_p2;
        add_ln16_5_reg_610 <= add_ln16_5_fu_332_p2;
        add_ln16_7_reg_615 <= add_ln16_7_fu_338_p2;
        select_ln10_1_reg_580 <= select_ln10_1_fu_304_p3;
        select_ln10_2_reg_586 <= select_ln10_2_fu_309_p3;
        zext_ln16_1_reg_603[2 : 0] <= zext_ln16_1_fu_326_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln10_2_reg_685 <= add_ln10_2_fu_419_p2;
        add_ln16_3_reg_770 <= add_ln16_3_fu_492_p2;
        add_ln16_6_reg_695 <= add_ln16_6_fu_428_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_reg_552 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln10_4_reg_630 <= add_ln10_4_fu_367_p2;
        add_ln16_8_reg_645 <= add_ln16_8_fu_380_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln10_fu_246_p2 == 1'd0))) begin
        add_ln10_reg_556 <= add_ln10_fu_261_p2;
        empty_7_reg_575 <= empty_7_fu_293_p2;
        icmp_ln12_reg_561 <= icmp_ln12_fu_267_p2;
        select_ln10_reg_567 <= select_ln10_fu_273_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln16_1_reg_755 <= grp_fu_500_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln16_2_reg_765 <= grp_fu_514_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln16_9_reg_725 <= add_ln16_9_fu_475_p2;
        add_ln16_9_reg_725_pp0_iter3_reg <= add_ln16_9_reg_725;
        empty_reg_547 <= empty_fu_240_p2;
        i_1_reg_542 <= ap_sig_allocacmp_i_1;
        icmp_ln10_reg_552 <= icmp_ln10_fu_246_p2;
        icmp_ln10_reg_552_pp0_iter1_reg <= icmp_ln10_reg_552;
        icmp_ln10_reg_552_pp0_iter2_reg <= icmp_ln10_reg_552_pp0_iter1_reg;
        mul_ln16_3_reg_735 <= grp_fu_409_p2;
        select_ln10_reg_567_pp0_iter1_reg <= select_ln10_reg_567;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln16_reg_760 <= grp_fu_507_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_ln16_1_reg_745 <= grp_fu_437_p2;
        select_ln10_1_reg_580_pp0_iter1_reg <= select_ln10_1_reg_580;
        select_ln10_2_reg_586_pp0_iter1_reg <= select_ln10_2_reg_586;
        zext_ln16_1_reg_603_pp0_iter1_reg[2 : 0] <= zext_ln16_1_reg_603[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_191 <= a_q0;
        reg_199 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_195 <= a_q1;
        reg_203 <= b_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_address0 = add_ln10_2_cast_fu_467_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_address0 = select_ln10_2_cast_fu_393_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_address0 = add_ln10_1_cast_fu_359_p1;
    end else begin
        a_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_address1 = add_ln10_4_cast_fu_385_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_address1 = add_ln10_3_cast_fu_363_p1;
    end else begin
        a_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        a_ce0 = 1'b1;
    end else begin
        a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        a_ce1 = 1'b1;
    end else begin
        a_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_reg_552 == 1'd1) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln10_reg_552_pp0_iter2_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 3'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_address0 = zext_ln16_4_fu_471_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_address0 = zext_ln12_fu_401_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_address0 = zext_ln16_3_fu_372_p1;
    end else begin
        b_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_address1 = zext_ln16_6_fu_389_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_address1 = zext_ln16_5_fu_376_p1;
    end else begin
        b_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        b_ce0 = 1'b1;
    end else begin
        b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        b_ce1 = 1'b1;
    end else begin
        b_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prod_ce0 = 1'b1;
    end else begin
        prod_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prod_we0 = 1'b1;
    end else begin
        prod_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_1_cast_fu_359_p1 = add_ln10_1_reg_593;

assign add_ln10_1_fu_314_p2 = (select_ln10_2_fu_309_p3 + 5'd1);

assign add_ln10_2_cast_fu_467_p1 = add_ln10_2_reg_685;

assign add_ln10_2_fu_419_p2 = (select_ln10_2_reg_586_pp0_iter1_reg + 5'd2);

assign add_ln10_3_cast_fu_363_p1 = add_ln10_3_reg_598;

assign add_ln10_3_fu_320_p2 = (select_ln10_2_fu_309_p3 + 5'd3);

assign add_ln10_4_cast_fu_385_p1 = add_ln10_4_reg_630;

assign add_ln10_4_fu_367_p2 = (select_ln10_2_reg_586 + 5'd4);

assign add_ln10_5_fu_252_p2 = (ap_sig_allocacmp_indvar_flatten_load + 5'd1);

assign add_ln10_cast_fu_281_p1 = add_ln10_fu_261_p2;

assign add_ln10_fu_261_p2 = (ap_sig_allocacmp_i_1 + 3'd1);

assign add_ln12_fu_344_p2 = (select_ln10_reg_567 + 3'd1);

assign add_ln16_3_fu_492_p2 = ($signed(add_ln16_2_reg_765) + $signed(add_ln16_reg_760));

assign add_ln16_4_fu_457_p2 = (tmp_2_fu_450_p3 + zext_ln16_fu_447_p1);

assign add_ln16_5_fu_332_p2 = (zext_ln16_2_fu_329_p1 + 4'd5);

assign add_ln16_6_fu_428_p2 = (zext_ln16_1_reg_603_pp0_iter1_reg + 5'd10);

assign add_ln16_7_fu_338_p2 = (zext_ln16_1_fu_326_p1 + 5'd15);

assign add_ln16_8_fu_380_p2 = ($signed(zext_ln16_1_reg_603) + $signed(5'd20));

assign add_ln16_9_fu_475_p2 = (add_ln16_4_fu_457_p2 + zext_ln16_1_reg_603_pp0_iter1_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_150 = ((icmp_ln10_reg_552 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_292 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_573 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign empty_7_fu_293_p2 = (tmp_1_fu_285_p3 + add_ln10_cast_fu_281_p1);

assign empty_fu_240_p2 = (tmp_fu_232_p3 + i_cast_fu_228_p1);

assign i_cast_fu_228_p1 = ap_sig_allocacmp_i_1;

assign icmp_ln10_fu_246_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_267_p2 = ((ap_sig_allocacmp_j_load == 3'd5) ? 1'b1 : 1'b0);

assign prod_address0 = zext_ln16_7_fu_496_p1;

assign prod_d0 = add_ln16_3_reg_770;

assign select_ln10_1_fu_304_p3 = ((icmp_ln12_reg_561[0:0] == 1'b1) ? add_ln10_reg_556 : i_1_reg_542);

assign select_ln10_2_cast_fu_393_p1 = select_ln10_2_reg_586;

assign select_ln10_2_fu_309_p3 = ((icmp_ln12_reg_561[0:0] == 1'b1) ? empty_7_reg_575 : empty_reg_547);

assign select_ln10_fu_273_p3 = ((icmp_ln12_fu_267_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_j_load);

assign tmp_1_fu_285_p3 = {{add_ln10_fu_261_p2}, {2'd0}};

assign tmp_2_fu_450_p3 = {{select_ln10_1_reg_580_pp0_iter1_reg}, {2'd0}};

assign tmp_fu_232_p3 = {{ap_sig_allocacmp_i_1}, {2'd0}};

assign zext_ln12_fu_401_p1 = select_ln10_reg_567_pp0_iter1_reg;

assign zext_ln16_1_fu_326_p1 = select_ln10_reg_567;

assign zext_ln16_2_fu_329_p1 = select_ln10_reg_567;

assign zext_ln16_3_fu_372_p1 = add_ln16_5_reg_610;

assign zext_ln16_4_fu_471_p1 = add_ln16_6_reg_695;

assign zext_ln16_5_fu_376_p1 = add_ln16_7_reg_615;

assign zext_ln16_6_fu_389_p1 = add_ln16_8_reg_645;

assign zext_ln16_7_fu_496_p1 = add_ln16_9_reg_725_pp0_iter3_reg;

assign zext_ln16_fu_447_p1 = select_ln10_1_reg_580_pp0_iter1_reg;

always @ (posedge ap_clk) begin
    zext_ln16_1_reg_603[4:3] <= 2'b00;
    zext_ln16_1_reg_603_pp0_iter1_reg[4:3] <= 2'b00;
end

endmodule //matrix_mult
